name: Build
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-20.04

    env:
      BUILD_DIR: "./build"
      BAZEL_VER: "6.3.2"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bazel
        run: |
          sudo apt-get update && apt-get install -y apt-transport-https curl gnupg && \
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings && \
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list && \
          apt-get update && apt-get install -y bazel-${BAZEL_VER}

      - name: Build the software
        run: |
          if [ -d $BUILD_DIR ]; then
            rm -r $BUILD_DIR 
          fi
          mkdir $BUILD_DIR 
          bazel build src:main --verbose_failures
          mv ./bazel* $BUILD_DIR

      - name: Run the software
        run: |
          bazel run src:main
          mv ./bazel* $BUILD_DIR