name: Deploy
run-name: Deploy the software
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    env:
      BUILD_DIR: "./build"
      BAZEL_VER: "6.3.2"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bazel
        run: |
          sudo apt-get install apt-transport-https curl gnupg -y
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update && sudo apt-get install -y bazel-${BAZEL_VER}

      - name: Build the software
        run: |
          if [ -d $BUILD_DIR ]; then
            rm -r $BUILD_DIR 
          fi
          mkdir $BUILD_DIR 
          bazel build src:app --verbose_failures
          mv ./bazel* $BUILD_DIR

      - name: Prepare the artifacts
          run: |
            sudo cp $BUILD_DIR/bazel-bin/src/app $BUILD_DIR/bazel-bin/src/app.exe

      - name: Deploy the artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: app
          path: ./build/bazel-bin/src/app.exe
