name: Docker
run-name: Build docker image
on:
    workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04

    env: 
        DOCKER_IMAGE: "bazel-app"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the image
        run: |
            docker build . -t bazel-app

      - name: Push the image on Docker hub
        run: |
            docker tag $DOCKER_IMAGE:latest ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMAGE
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMAGE:latest
